param userAssignedIdentities_LOBAppExpiryNotifications_Identity_name string = 'LOBAppExpiryNotifications-ManagedIdentity'
param resourceLocation string 

resource userAssignedIdentities_LOBAppExpiryNotifications_Identity_name_resource 'Microsoft.ManagedIdentity/userAssignedIdentities@2018-11-30' = {
  name: userAssignedIdentities_LOBAppExpiryNotifications_Identity_name
  location: resourceLocation
}
